# Generated by Django 3.0.7 on 2020-08-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, null=True)),
                ('passwod', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, null=True)),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField(null=True)),
                ('puplished', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
